name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Run Jest & Supertest Tests
      run: npm test
      env:
        NODE_ENV: test
        MONGO_URI: ${{ secrets.MONGO_URI }}
        JWT_SECRET: "test-jwt-secret-for-ci"

    - name: Deploy to AWS EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          if [ -d ~/app ]; then
            cd ~/app
            git pull origin main
          else
            git clone https://github.com/shruti-4002/Secure-Pay-Core-backend.git ~/app
            cd ~/app
          fi

          echo "${{ secrets.PRODUCTION_ENV_FILE }}" > .env
          
          docker compose down
          docker compose up -d --build